### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by GaetanBenoitDev** [LuoGroup2023/DeChat#4]
Hi,

The program crashed during read correction step. I used this public dataset: ERR7256374 (it's a metagenomics R10.4 dataset).
https://www.ebi.ac.uk/ena/browser/view/ERR7256374

I used default parameters

**Comment by LuoGroup2023** [comment]
> Hi,
> 
> The program crashed during read correction step. I used this public dataset: ERR7256374 (it's a metagenomics R10.4 dataset). https://www.ebi.ac.uk/ena/browser/view/ERR7256374
> 
> I used default parameters

Hello, 

could you please provide detailed output logs so that I can quickly identify potential issues?
Also, I will download the data you used for testing.

**Comment by LuoGroup2023** [comment]
> Hi,
> 
> The program crashed during read correction step. I used this public dataset: ERR7256374 (it's a metagenomics R10.4 dataset). https://www.ebi.ac.uk/ena/browser/view/ERR7256374
> 
> I used default parameters
Hi，

I apologize for the delayed response; I have been occupied with other matters recently. I encountered a "malloc(): invalid size (unsorted)" error while testing the dataset ERR7256374. However, after filtering the data to allow a minimum length of 1000, the issue no longer occurred. This error is likely due to a third-party library I am using, and I am working diligently to resolve it. In the meantime, you can try filtering the data to sequences of at least 1000 in length, which should address the issue for your needs. I hope this solution is helpful.

**Comment by LuoGroup2023** [comment]
> > Hi,
> > The program crashed during read correction step. I used this public dataset: ERR7256374 (it's a metagenomics R10.4 dataset). https://www.ebi.ac.uk/ena/browser/view/ERR7256374
> > I used default parameters
> > Hi，
> 
> I apologize for the delayed response; I have been occupied with other matters recently. I encountered a "malloc(): invalid size (unsorted)" error while testing the dataset ERR7256374. However, after filtering the data to allow a minimum length of 1000, the issue no longer occurred. This error is likely due to a third-party library I am using, and I am working diligently to resolve it. In the meantime, you can try filtering the data to sequences of at least 1000 in length, which should address the issue for your needs. I hope this solution is helpful.


The latest version of dechat has been uploaded, fixing potential errors encountered during the generation of recorrected.fa. Updates for the conda environment submissions will follow. You can compile locally to run the latest version of dechat.
